// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmMessageChange();
void onHumidityChange();
void onTemperatureChange();
void onAlarmTriggerChange();

String alarmMessage;
float humidity;
float temperature;
bool alarmTrigger;

void initProperties(){

  ArduinoCloud.addProperty(alarmMessage, READWRITE, ON_CHANGE, onAlarmMessageChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(alarmTrigger, READWRITE, ON_CHANGE, onAlarmTriggerChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
