// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDistanceCmChange();

float distance_cm;

void initProperties(){

  ArduinoCloud.addProperty(distance_cm, READWRITE, ON_CHANGE, onDistanceCmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
